# Generated by Django 4.2.5 on 2023-09-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_info',
            new_name='short_intro',
        ),
    ]
