# Generated by Django 4.2.5 on 2023-10-05 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_suject_message_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
